name: openapi_spec
description: OpenAPI Specification generator using native Dart code, as well as an all-in-one parser of existing specifications.
version: 0.7.8
maintainer: Taza Technology LLC
repository: https://github.com/tazatechnology/openapi_spec
issue_tracker: https://github.com/tazatechnology/openapi_spec/issues
homepage: https://tazatechnology.com
documentation: https://github.com/tazatechnology/openapi_spec

environment:
  sdk: ^3.8.0

dependencies:
  collection: ^1.17.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.8.1
  yaml: ^3.1.2
  path: ^1.8.3
  
  # For generated client code
  intl: ">=0.17.0 <1.0.0"
  http: ">=0.13.0 <2.0.0"
  recase: ^4.1.0
  
dev_dependencies:
  build_runner: ^2.5.4
  lints: ^6.0.0
  freezed: ^2.5.8
  json_serializable: ^6.9.5
  test: ^1.24.7
  